#!/usr/bin/env node
// Copies contract ABIs from Foundry build artifacts into typed TypeScript modules.
//
// Usage (from web/):  node scripts/sync-abi.mjs <ContractName> [<ContractName> ...]
//   (`npm run sync-abi` passes this repo's contract names; run `forge build` first.)
//
// For every name it reads  ../out/<Name>.sol/<Name>.json  and writes
//   src/abi/<name>.ts  ->  export const <name>Abi = [...] as const
// where <name> is the contract name with a lower-case first letter. The full ABI is kept,
// including `error` entries, so viem can decode custom errors. src/abi/index.ts re-exports all.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const webDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = resolve(webDir, '..', 'out')
const abiDir = resolve(webDir, 'src', 'abi')

const names = process.argv.slice(2)
if (names.length === 0) {
  console.error('usage: node scripts/sync-abi.mjs <ContractName> [<ContractName> ...]')
  process.exit(1)
}

mkdirSync(abiDir, { recursive: true })
const header = '// AUTO-GENERATED by web/scripts/sync-abi.mjs. Do not edit by hand.\n'
const reexports = []

for (const name of names) {
  const artifactPath = resolve(outDir, `${name}.sol`, `${name}.json`)
  let artifact
  try {
    artifact = JSON.parse(readFileSync(artifactPath, 'utf8'))
  } catch {
    console.error(`missing artifact ${relative(webDir, artifactPath)}; run \`forge build\` in the repo root first`)
    process.exit(1)
  }
  if (!Array.isArray(artifact.abi)) {
    console.error(`artifact ${artifactPath} has no abi array`)
    process.exit(1)
  }
  const base = name.charAt(0).toLowerCase() + name.slice(1)
  const body =
    `${header}// Source: out/${name}.sol/${name}.json\n\n` +
    `export const ${base}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const\n`
  writeFileSync(resolve(abiDir, `${base}.ts`), body)
  reexports.push(`export { ${base}Abi } from './${base}'`)
  const errors = artifact.abi.filter((e) => e.type === 'error').length
  console.log(`wrote src/abi/${base}.ts (${artifact.abi.length} entries, ${errors} errors)`)
}

writeFileSync(resolve(abiDir, 'index.ts'), `${header}\n${reexports.join('\n')}\n`)
console.log('wrote src/abi/index.ts')
