// AUTO-GENERATED by web/scripts/sync-abi.mjs. Do not edit by hand.

export { stellarOracleAbi } from './stellarOracle'
export { stellarPredictAbi } from './stellarPredict'
export { iVladTokenAbi } from './iVladToken'
